using Content.Shared._DV.CosmicCult.Components;
using Content.Shared._DV.CosmicCult.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.CosmicCult.UI.CosmicShop;

[GenerateTypedNameReferences]
public sealed partial class InfluenceButtonContainer : BoxContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private readonly SpriteSystem _sprite;

    public Action? OnDetailButtonPressed;
    public readonly InfluenceUIBox.InfluenceUIBoxState State;
    public readonly InfluencePrototype Proto;

    public InfluenceButtonContainer(InfluencePrototype influenceProto, InfluenceUIBox.InfluenceUIBoxState state)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entityManager.System<SpriteSystem>();

        DetailButton.TextureNormal = _sprite.Frame0(influenceProto.Icon);
        DetailButton.ToolTip = Loc.GetString(influenceProto.Name);

        State = state;
        Proto = influenceProto;

        var availableEntropy = 0;
        if (_entityManager.TryGetComponent<CosmicCultComponent>(_playerManager.LocalEntity, out var cultComp))
            availableEntropy = cultComp.EntropyBudget;

        switch (state)
        {
            case InfluenceUIBox.InfluenceUIBoxState.Owned:
                DetailButton.Modulate = Color.Green;
                break;

            case InfluenceUIBox.InfluenceUIBoxState.UnlockedAndEnoughEntropy:
                DetailButton.Modulate = Color.White;
                break;

            case InfluenceUIBox.InfluenceUIBoxState.UnlockedAndNotEnoughEntropy:
            case InfluenceUIBox.InfluenceUIBoxState.Locked:
                DetailButton.Modulate = Color.Gray;
                break;
        }

        DetailButton.OnPressed += _ => OnDetailButtonPressed?.Invoke();
    }
}
